# CLASS 4

# How to count the number of files in a directory using Python

In [59]:
import numpy as np
images= np.zeros([20,200,200,2])

In [ ]:
import os, os.path

# simple version for working with CWD
print len([name for name in os.listdir('.') if os.path.isfile(name)])

# path joining version for other paths
DIR = '/tmp'
print len([name for name in os.listdir(DIR) if os.path.isfile(os.path.join(DIR, name))])

In [ ]:
import os

path, dirs, files = next(os.walk("/usr/lib"))
file_count = len(files)

In [ ]:
#For all kind of files, subdirectories included:

import os

list = os.listdir(dir) # dir is your directory path
number_files = len(list)
print number_files

#Only files (avoiding subdirectories):

import os

onlyfiles = next(os.walk(dir))[2] #dir is your directory path as string
print len(onlyfiles)

# PANDAS

In [ ]:
Series,Data Frame
series looks like 1d while data frame multi-d

In [6]:
import pandas as pd

In [8]:
obj = pd.Series([4,7,-5,3])
print(obj)

#printing values with its index

0    4
1    7
2   -5
3    3
dtype: int64


In [9]:
obj.values #attributes because of having no bracket

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [23]:
mnth = pd.Series([100,200,300,400],index=['jan','feb','march','apr'],name="changing index name")
print(mnth)
print(mnth.values)
print(mnth.index)

jan      100
feb      200
march    300
apr      400
Name: changing index name, dtype: int64
[100 200 300 400]
Index(['jan', 'feb', 'march', 'apr'], dtype='object')


In [24]:
MnthNames=['jan','feb','march','apr']
mnth = pd.Series([100,200,300,400],index=MnthNames,name="changing index name")
print(mnth)
print(mnth.values)
print(mnth.index)

#storing any values to respective index

jan      100
feb      200
march    300
apr      400
Name: changing index name, dtype: int64
[100 200 300 400]
Index(['jan', 'feb', 'march', 'apr'], dtype='object')


In [81]:
DayNames=['mon','tue','wed','thurs','fri','sat','sun']
Canteen = pd.Series([20,30,20,25,30,40,0],index=DayNames,name="Canteen data")
print(Canteen)

print(Canteen[ ["mon","fri"] ])
print(Canteen[ [1,4] ])

mon      20
tue      30
wed      20
thurs    25
fri      30
sat      40
sun       0
Name: Canteen data, dtype: int64
mon    20
fri    30
Name: Canteen data, dtype: int64
tue    30
fri    30
Name: Canteen data, dtype: int64


In [82]:
"mon" in Canteen

True

In [83]:
print([Canteen>20])

[mon      False
tue       True
wed      False
thurs     True
fri       True
sat       True
sun      False
Name: Canteen data, dtype: bool]


In [27]:
print(Canteen["tue"]) #accesing the value with modified index

30


In [28]:
print(Canteen[1]) #accessing value with pre-defined index

30


In [29]:
import calendar

for month_idx in range(1, 13):
    print (calendar.month_name[month_idx])
    print (calendar.month_abbr[month_idx])
    print ("")

January
Jan

February
Feb

March
Mar

April
Apr

May
May

June
Jun

July
Jul

August
Aug

September
Sep

October
Oct

November
Nov

December
Dec



In [76]:
values= np.random.randint(10,101,size=[12])
months = []
for i in range(1,13):
    mnths=calendar.month_abbr[i]
    months.append(mnths)
    
demo = pd.Series(values,
                 index = months)

print(demo)

Jan    43
Feb    45
Mar    56
Apr    48
May    56
Jun    16
Jul    92
Aug    98
Sep    66
Oct    91
Nov    24
Dec    94
dtype: int32
